export const TYPES = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    SET_CURRENT_USER_SUCCESS : 'SET_CURRENT_USER_SUCCESS',
    SET_CURRENT_USER_FAILURE : 'SET_CURRENT_USER_FAILURE',
    SET_CURRENT_USER_START : 'SET_CURRENT_USER_START',
    LOGOUT_USER:'LOGOUT_USER',
    LOGOUT_USER_START : 'LOGOUT_USER_START',
    LOGOUT_USER_SUCCESS : 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILURE : 'LOGOUT_USER_FAILURE',
    SIGN_IN_WITH_GOOGLE_START : 'SIGN_IN_WITH_GOOGLE',
    SIGN_IN_WITH_EMAIL_START:'SIGN_IN_WITH_EMAIL',
    SIGN_UP_WITH_EMAIL : 'SIGN_UP_WITH_EMAIL',
    USER_SESSION_START : 'USER_SESSION_START'
};

