export const TYPES = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SET_PRODUCTS_START : 'SET_PRODUCTS_START',
    SET_PRODUCTS_SUCCESS : 'SET_PRODUCTS_SUCCESS',
    SET_PRODUCTS_FAILURE : 'SET_PRODUCTS_FAILURE'
}